name: authentication_module
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  http: ^1.6.0
  carousel_slider_plus: ^7.1.2
  google_nav_bar: ^5.0.7
  intl_phone_field: ^3.2.0
  country_state_city_picker: ^2.0.0
  csc_picker: ^0.2.7
  country_state_city: ^0.1.6
  image_picker: ^1.1.2
  image_cropper: ^8.0.3
  flutter_native_splash: ^2.4.3
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/products/
    - .env

flutter_native_splash:
  color: "#FFFFFF" # Your app background color (e.g., White or AppColors.white hex code)
  image: "assets/images/logo.png" # Path to your app logo image
  android_12:
    color: "#FFFFFF"
    image: "assets/images/logo.png"